apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: webinar-synopsys
  type: core.Directory
  children:
    - name: webinar-synopsys-ecs-fargate-cluster
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
# ECS cluster (no instances, FARGATE only)
        - name: ecs-cluster
          type: aws.ecs.ClusterSpec
          clusterName: 'webinar-synopsys-ecs-cluster'
          region: 'us-east-2'
# Networking
        - name: webinar-synopsys-ecs-vpc
          type: aws.vpc.VPCSpec
          vpcName: 'webinar-synopsys-ecs-vpc'
          region: 'us-east-2'
          cidrBlock: 10.0.0.0/16
          createInternetGateway: true
          internetGatewayName: 'webinar-synopsys-ecs-igw'
        - name: webinar-synopsys-ecs-subnet-ipv4-az-1a
          type: aws.vpc.SubnetSpec
          subnetName: 'webinar-synopsys-ecs-subnet-ipv4-az-1a'
          region: 'us-east-2'
          availabilityZone: 'us-east-2a'
          vpc: 'Name:webinar-synopsys-ecs-vpc'
          cidrBlock: 10.0.0.0/24
        - name: webinar-synopsys-ecs-subnet-ipv4-az-1b
          type: aws.vpc.SubnetSpec
          subnetName: 'webinar-synopsys-ecs-subnet-ipv4-az-1b'
          region: 'us-east-2'
          availabilityZone: 'us-east-2b'
          vpc: 'Name:webinar-synopsys-ecs-vpc'
          cidrBlock: 10.0.1.0/24
        - name: webinar-synopsys-ecs-route-table
          type: aws.vpc.RouteTableSpec
          routeTableName: 'webinar-synopsys-ecs-route-table'
          region: 'us-east-2'
          vpc: 'Name:webinar-synopsys-ecs-vpc'
          is_main: true
          subnets:
          - 'Name:webinar-synopsys-ecs-subnet-ipv4-az-1a'
          - 'Name:webinar-synopsys-ecs-subnet-ipv4-az-1b'
          routes:
          - name: route1
            type: aws.vpc.RouteSpec
            ipv4Address: 0.0.0.0/0
            gatewayId: 'Name:webinar-synopsys-ecs-igw'
        - name: webinar-synopsys-ecs-security-group
          type: aws.vpc.SecurityGroupSpec
          securityGroupName: 'webinar-synopsys-ecs-security-group'
          description: Created by XL Deploy
          region: 'us-east-2'
          vpc: 'Name:webinar-synopsys-ecs-vpc'
          inboundRules:
          - name: inbound
            type: aws.vpc.SecurityGroupInboundRuleSpec
            protocol: -1
            portRange: 22
            source: 0.0.0.0/0