---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: InsecureBank
    type: udm.Application
    children:
      - name: Applications/InsecureBank/1.0.0
        type: udm.DeploymentPackage
        deployables:
        - name: insecure-bank
          type: tomcat.War
          file: !file "insecure-bank.war"
          contextRoot: /
          scanPlaceholders: true
        - name: docker-insecure-bank-web
          type: docker.ContainerSpec
          containerName: insecure-bank
          image: vlussenburg/insecure-bank-web:1.0.0
          environment:
            SEEKER_SERVER_URL: "{{SEEKER_SERVER_URL}}"
            JAVA_TOOL_OPTIONS: "{{JAVA_TOOL_OPTIONS}}"
            SEEKER_PROJECT_VERSION: "1.0.0"
          showLogsAfter: "5"
          portBindings:
          - name: pm-8080
            type: docker.PortSpec
            hostPort: "8080"
            containerPort: "8080"
          volumeBindings:
          - name: seeker-agent
            type: docker.MountedVolumeSpec
            volumeName: /opt/seeker-agent/seeker
            mountpoint: /seeker
            readOnly: true
---

apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/host
  type: overthere.LocalHost
  os: UNIX
- name: docker
  type: docker.Engine
  dockerHost: !value DOCKER_HOST
---

apiVersion: xl-deploy/v1
kind: Environments
spec:
  - name: insecure-bank-dict
    type: udm.Dictionary
    entries:
      APPLICATION_NAME: bois
      JAVA_TOOL_OPTIONS: "-javaagent:/seeker/seeker-agent.jar -Dseeker.project.key=\"{{APPLICATION_NAME}}\""
      SEEKER_SERVER_URL: https://ec2-18-218-251-228.us-east-2.compute.amazonaws.com:9912
  - name: Environments/dev
    type: udm.Environment
    members:
    - ~Infrastructure/docker
    dictionaries:
    - Environments/insecure-bank-dict